### ISSUE TITLE
No Sql file and controller issue

### ISSUE THREAD

**Issue by unionolivia** [m-peko/canDoIt#1]
I would be glad if you sent add DB SQL file to the folder.
Also, I get this error running it on my browser:
Fatal error: Uncaught Exception: Method index of class CandoitController does not exist. in candoit/lib/app.class.php:40 Stack trace: #0 /candoit/webroot/index.php(17): App::run('/candoit/') #1 {main} thrown in /candoit/lib/app.class.php on line 4

please can you figure it out.
Thanks

**Comment by m-peko** [comment]
Hi @unionolivia ,
Sorry for late response.
Sql file is added to repo. So far it has only users table but feel free to append it.
Regarding the fatal error you mentioned: if you are using XAMPP as your local server, you can avoid this
by changing httpd.conf file (xampp/apache/conf/httpd.conf). You must change lines 244 and 245
from 

> DocumentRoot "C:/xampp/htdocs/"
> <Directory "C:/xampp/htdocs/">

to

> DocumentRoot "C:/xampp/htdocs/canDoIt/"
> <Directory "C:/xampp/htdocs/canDoIt/">

Or simply set up virtual host.

If this solves your problem, please close the issue.
Thanks and contribute

**Comment by unionolivia** [comment]
I will try and update you.

Thanks Boss!
